apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-content
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>uat</title>
    </head>
    <body>

    <h1>{{ .Values.environment }}</h1>

    </body>
    </html>
