---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}
